CREATE TABLE `users` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`name` varchar(50),
	`email` varchar(50),
	`phone` char(15),
	`age` smallint,
	`gender` char(1),
	`occupation` varchar(100),
	`password` char(60),
	`salt` char(32),
	`is_email_verified` boolean DEFAULT false,
	`is_phone_verified` boolean DEFAULT false,
	`registered_using` enum('EMAIL','PHONE'),
	`picture` varchar(255),
	`designation` varchar(255),
	`bio` text,
	`country_code` char(2),
	`dial_code` char(5),
	`last_visited_at` timestamp(3) NOT NULL DEFAULT (now()),
	`updated_at` timestamp(3),
	`created_at` timestamp(3) NOT NULL DEFAULT (now()),
	`updated_by` int NOT NULL,
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`),
	CONSTRAINT `users_phone_unique` UNIQUE(`phone`)
);
